// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class AlbumType
{
    public int Album_TypeID { get; set; }

    public string Album_TypeDesc { get; set; }

    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();
}