// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Album
{
    public int Album_ID { get; set; }

    public string Album_Title { get; set; }

    public string Album_ArtistName { get; set; }

    public int Album_TypeID { get; set; }

    public int Album_Stock { get; set; }

    public byte[] Album_Cover { get; set; }

    public virtual AlbumType Album_Type { get; set; }
}